VERSION: str
NAME: str
BANNER: str
__version__: str

class Fabric:
    banner: str
    version: str
    good: bool
    silent: str | None
    locations: tuple[str, ...]
    modules: tuple[str, ...]
    features: dict[str, tuple[str, ...]]

    def __init__(
        self,
        locations: str | list[str] | tuple[str, ...] | None = None,
        modules: str | list[str] | tuple[str, ...] | None = None,
        silent: str | None = None,
        _withGc: bool = False,
    ) -> None: ...
    def load(
        self,
        features: str | list[str] | tuple[str, ...] | None = None,
        add: bool = False,
        silent: str | None = None,
    ) -> Corpus: ...
    def loadAll(self, silent: str | None = None) -> Corpus: ...
    def load_all(self, silent: str | None = None) -> Corpus: ...
    def compile(
        self,
        output_path: str,
        features: str | list[str] | tuple[str, ...] | None = None,
        silent: str | None = None,
    ) -> bool: ...
    def explore(self, silent: str | None = None, show: bool = True) -> dict[str, tuple[str, ...]]: ...
    def isLoaded(
        self,
        features: str | list[str] | tuple[str, ...] | None = None,
        pretty: bool = True,
        valueType: bool = True,
        path: bool = False,
        meta: str = "description",
    ) -> bool: ...
    def save(self, node_features: bool = True, edge_features: bool = True) -> bool: ...
    def loadCompiled(self, cache_path: str) -> Corpus: ...
    def load_compiled(self, cache_path: str) -> Corpus: ...
    def openMapped(self, cache_path: str) -> MappedCorpus: ...
    def open_mapped(self, cache_path: str) -> MappedCorpus: ...

class MappedCorpus:
    maxNode: int

    def Fall(self, warp: bool = True) -> tuple[str, ...]: ...
    def Eall(self, warp: bool = True) -> tuple[str, ...]: ...
    def Call(self) -> tuple[str, ...]: ...
    def search(
        self,
        template: str,
        limit: int | None = None,
    ) -> tuple[tuple[int, ...], ...]: ...

class Corpus:
    F: NodeFeatures
    E: EdgeFeatures
    L: Locality
    N: Nodes
    T: Text
    S: Search
    C: Computeds

    def node_feature_names(self) -> tuple[str, ...]: ...
    def edge_feature_names(self) -> tuple[str, ...]: ...
    def Fall(self, warp: bool = True) -> tuple[str, ...]: ...
    def Eall(self, warp: bool = True) -> tuple[str, ...]: ...
    def Call(self) -> tuple[str, ...]: ...
    def Fs(self, name: str, warn: bool = True) -> NodeFeature | None: ...
    def Es(self, name: str, warn: bool = True) -> EdgeFeature | None: ...
    def Cs(self, name: str | None = None) -> Computeds | Computed: ...
    def isLoaded(
        self,
        features: str | list[str] | tuple[str, ...] | None = None,
        pretty: bool = True,
        valueType: bool = True,
        path: bool = False,
        meta: str = "description",
    ) -> bool: ...
    def ensureLoaded(self, features: str | list[str] | tuple[str, ...] | None = None) -> bool: ...
    def makeAvailableIn(self, scope: dict[str, object]) -> None: ...
    def footprint(self, recompute: bool = False, by_size: bool = True) -> str: ...

class NodeFeatures:
    def __getattr__(self, name: str) -> NodeFeature: ...

class EdgeFeatures:
    def __getattr__(self, name: str) -> EdgeFeature: ...

class NodeFeature:
    name: str
    metaData: dict[str, str | None]
    meta: dict[str, str | None]
    data: dict[int, str | int]
    valueType: str | None
    description: str | None
    slotType: str | None
    maxSlot: int | None
    maxNode: int | None

    def v(self, node: int) -> str | int | None: ...
    def s(self, value: str | int) -> tuple[int, ...]: ...
    def items(self) -> tuple[tuple[int, str | int], ...]: ...
    def freq_list(self, node_types: object | None = None) -> tuple[tuple[str | int, int], ...]: ...
    def freqList(self, node_types: object | None = None) -> tuple[tuple[str | int, int], ...]: ...

class EdgeFeature:
    name: str
    metaData: dict[str, str | None]
    meta: dict[str, str | None]
    data: dict[int, tuple[int, ...] | dict[int, str | int | None]]
    dataInv: dict[int, tuple[int, ...] | dict[int, str | int | None]]
    valueType: str | None
    description: str | None
    doValues: bool

    def f(self, node: int) -> tuple[int | tuple[int, str | int | None], ...]: ...
    def t(self, node: int) -> tuple[int | tuple[int, str | int | None], ...]: ...
    def s(self, node: int) -> tuple[int, ...]: ...
    def b(self, node: int) -> tuple[int | tuple[int, str | int | None], ...]: ...
    def items(self) -> tuple[tuple[int, tuple[int, ...]], ...]: ...
    def freq_list(
        self,
        node_types_from: object | None = None,
        node_types_to: object | None = None,
    ) -> int | tuple[tuple[str | int | None, int], ...]: ...
    def freqList(
        self,
        node_types_from: object | None = None,
        node_types_to: object | None = None,
    ) -> int | tuple[tuple[str | int | None, int], ...]: ...
    def has_edge_values(self) -> bool: ...
    def hasEdgeValues(self) -> bool: ...

class Locality:
    def u(self, node: int, otype: str | list[str] | tuple[str, ...] | set[str] | None = None) -> tuple[int, ...]: ...
    def d(self, node: int, otype: str | list[str] | tuple[str, ...] | set[str] | None = None) -> tuple[int, ...]: ...
    def n(self, node: int, otype: str | list[str] | tuple[str, ...] | set[str] | None = None) -> tuple[int, ...]: ...
    def p(self, node: int, otype: str | list[str] | tuple[str, ...] | set[str] | None = None) -> tuple[int, ...]: ...
    def i(self, node: int, otype: str | list[str] | tuple[str, ...] | set[str] | None = None) -> tuple[int, ...]: ...

class Nodes:
    otypeRank: dict[str, int]

    def sortKey(self, node: int) -> int: ...
    def sortKeyTuple(self, nodes: list[int] | tuple[int, ...] | set[int]) -> tuple[int, ...]: ...
    def sortNodes(self, nodes: list[int] | tuple[int, ...] | set[int]) -> tuple[int, ...]: ...
    def walk(
        self,
        nodes: list[int] | tuple[int, ...] | set[int] | None = None,
        events: bool = False,
    ) -> tuple[int, ...]: ...

class Text:
    sectionTypes: tuple[str, ...]
    sectionFeatures: tuple[str, ...]
    sectionFeats: tuple[str, ...]
    formats: tuple[str, ...]
    structureTypes: tuple[str, ...]
    structureFeats: tuple[str, ...]
    languages: tuple[str, ...]
    headings: dict[object, object]

    def text(
        self,
        node: int,
        fmt: str | None = None,
        descend: bool | None = None,
    ) -> str: ...
    def sectionFromNode(
        self,
        node: int,
        lastSlot: bool = False,
        fillup: bool = False,
        level: int | None = None,
        lang: str = "en",
    ) -> tuple[str | int | None, ...]: ...
    def sectionTuple(
        self,
        node: int,
        lastSlot: bool = False,
        fillup: bool = False,
        level: int | None = None,
        lang: str = "en",
    ) -> tuple[str | int | None, ...]: ...
    def nodeFromSection(
        self,
        section: tuple[str | int, ...],
        lang: str = "en",
    ) -> int | None: ...
    def headingFromNode(self, node: int) -> tuple[tuple[str, str], ...] | None: ...
    def nodeFromHeading(self, heading: tuple[tuple[str, str | int], ...]) -> int | None: ...
    def structure(self, node: int | None = None) -> object | None: ...
    def top(self) -> tuple[int, ...] | None: ...
    def up(self, node: int) -> tuple[int, ...]: ...
    def down(self, node: int) -> tuple[int, ...]: ...
    def structurePretty(self, node: int | None = None, fullHeading: bool = False) -> str | None: ...
    def bookName(self, node: int, lang: str = "en") -> str | None: ...
    def bookNode(self, name: str, lang: str = "en") -> int | None: ...

class Search:
    exe: SearchExe | None
    perfParams: dict[str, object]
    api: bool

    def study(self, template: str) -> None: ...
    def search(
        self,
        template: str,
        limit: int | None = None,
        sets: object | None = None,
        shallow: bool = False,
        silent: str | None = None,
        here: bool = False,
    ) -> tuple[tuple[int, ...], ...]: ...
    def fetch(self, limit: int | None = None) -> tuple[tuple[int, ...], ...]: ...
    def count(self, progress: int | None = None, limit: int | None = None) -> int: ...
    def showPlan(self, details: bool = False) -> str | None: ...
    def glean(self, tuples: object) -> tuple[object, ...]: ...
    def tweakPerformance(self) -> bool: ...
    def relationsLegend(self) -> str: ...

class SearchExe:
    good: bool
    badSyntax: list[tuple[int | None, str]]
    badSemantics: list[tuple[int | None, str]]

class Computed:
    data: object

class Computeds:
    levels: Computed
    order: Computed
    rank: Computed
    boundary: Computed
